center_of_mass_m:
- -0.01025
- -0.00206
- 0.03567
coordinate_system_note: Rigid body pose was transformed by R_GF = R_Y(180) before
  calibration.
description: Tool gravity calibration results based on motion capture data.
mass_kg: 0.20111
static_force_offset_N:
- -1.09997
- 1.29272
- -1.78449
static_torque_offset_Nm:
- -0.07577
- -0.65508
- -0.09023
