center_of_mass_m:
- -0.0149
- 0.0105
- 0.04091
coordinate_system_note: Rigid body pose was transformed by R_GF = R_Y(180) before
  calibration.
description: Tool gravity calibration results based on motion capture data.
mass_kg: 0.22198
static_force_offset_N:
- -0.62875
- -0.13113
- -3.02676
static_torque_offset_Nm:
- -0.02941
- -0.65378
- -0.0238
