center_of_mass_m:
- -0.0149
- 0.0105
- 0.04091
coordinate_system_note: Rigid body pose was transformed by R_GF = R_Y(180) before
  calibration.
description: Tool gravity calibration results based on motion capture data.
mass_kg: 0.22198
static_force_offset_N:
- -0.62875
- -0.13113
- -3.02676
static_torque_offset_Nm:
- -0.02941
- -0.65378
- -0.0238


T_robot_to_mocap:
- [0.999880, 0.015185, -0.003222, 0.576824]
- [-0.015229, 0.999783, -0.014241, 1.881803]
- [0.003005, 0.014289, 0.999893, 0.787360]
- [0.000000, 0.000000, 0.000000, 1.000000]

T_ee_to_tool:
- [1.000000, 0.000000, 0.000000, 0.000000]
- [0.000000, 1.000000, 0.000000, 0.090000]
- [0.000000, 0.000000, 1.000000, 0.237000]
- [0.000000, 0.000000, 0.000000, 1.000000]

T_sensor_to_ee:
- [1.000000, 0.000000, 0.000000, 0.000000]
- [0.000000, 1.000000, 0.000000, 0.000000]
- [0.000000, 0.000000, 1.000000, 0.000000]
- [0.000000, 0.000000, 0.000000, 1.000000]

T_cam_to_robot:
- [0.99812176, -0.03163668, 0.05246012, -0.48817377]
- [-0.05307836, -0.87417346, 0.48270431, -0.60946391]
- [0.03058809, -0.48458218, -0.87421078, 0.50653765]
- [0.00000000, 0.00000000, 0.00000000, 1.00000000]